### ISSUE TITLE
Credit unknown for /visualizer/js/webgl-programs.js

### ISSUE THREAD

**Issue by LivInTheLookingGlass** [gappleto97/dailyblockchain.github.io#19]
@anvaka @dailyblockchain

Which one of you wrote [this file](https://github.com/gappleto97/visualizer/blob/gh-pages/js/webgl-programs.js)? I assume it was anvaka, but I want to verify.

**Comment by anvaka** [comment]
this looks very much like minified version from this file: http://www.yasiv.com/scripts/yasiv.fb.min.js?v=0.27.9

But I don't think I ever released it publicly :)

**Comment by LivInTheLookingGlass** [comment]
Huh. Wonder how it got in there then.

Thanks!
